using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiniBus.AzureFunctions.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class MiniBusAzureFunctionsWrapperGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
// <auto-generated/>
#nullable enable

namespace MiniBus.AzureFunctions.SourceGenerators.Declarations
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
    internal sealed class MiniBusSourceGeneratedServiceBusQueueFunctionAttribute : global::System.Attribute
    {
        public MiniBusSourceGeneratedServiceBusQueueFunctionAttribute()
        {
        }

        public MiniBusSourceGeneratedServiceBusQueueFunctionAttribute(string functionName, string queueName, string connection)
        {
            FunctionName = functionName;
            QueueName = queueName;
            Connection = connection;
        }

        public string FunctionName { get; set; } = string.Empty;

        public string QueueName { get; set; } = string.Empty;

        public string Connection { get; set; } = string.Empty;
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
    internal sealed class MiniBusSourceGeneratedServiceBusTopicFunctionAttribute : global::System.Attribute
    {
        public MiniBusSourceGeneratedServiceBusTopicFunctionAttribute()
        {
        }

        public MiniBusSourceGeneratedServiceBusTopicFunctionAttribute(string functionName, string topicName, string subscriptionName, string connection)
        {
            FunctionName = functionName;
            TopicName = topicName;
            SubscriptionName = subscriptionName;
            Connection = connection;
        }

        public string FunctionName { get; set; } = string.Empty;

        public string TopicName { get; set; } = string.Empty;

        public string SubscriptionName { get; set; } = string.Empty;

        public string Connection { get; set; } = string.Empty;
    }
}
""";

    private static readonly DiagnosticDescriptor MissingRequiredValue = new(
        id: "MBFWR001",
        title: "MiniBus generated function declaration is missing a required value",
        messageFormat: "MiniBus {0} function declaration requires a non-empty {1}",
        category: "MiniBus.AzureFunctions.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NonConstantRequiredValue = new(
        id: "MBFWR003",
        title: "MiniBus generated function declaration value must be a constant string",
        messageFormat: "MiniBus {0} function declaration requires {1} to be a compile-time constant string",
        category: "MiniBus.AzureFunctions.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateFunctionName = new(
        id: "MBFWR002",
        title: "MiniBus generated function name must be unique",
        messageFormat: "MiniBus generated function name '{0}' is declared more than once",
        category: "MiniBus.AzureFunctions.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
        {
            output.AddSource("MiniBusAzureFunctionsTriggerAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        var declarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateAssemblyAttribute(node),
                transform: static (syntaxContext, cancellationToken) => CreateDeclaration(syntaxContext, cancellationToken))
            .Where(static declaration => declaration is not null)
            .Collect();

        context.RegisterSourceOutput(declarations, static (sourceProductionContext, declarations) =>
        {
            Execute(sourceProductionContext, declarations);
        });
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<FunctionDeclaration?> declarations)
    {
        if (declarations.IsDefaultOrEmpty)
        {
            return;
        }

        var functionDeclarations = declarations
            .Where(static declaration => declaration is not null)
            .Cast<FunctionDeclaration>()
            .ToArray();

        if (functionDeclarations.Length == 0)
        {
            return;
        }

        var invalidDeclarations = new HashSet<FunctionDeclaration>();
        foreach (var declaration in functionDeclarations)
        {
            foreach (var nonConstantValue in declaration.GetNonConstantRequiredValues())
            {
                invalidDeclarations.Add(declaration);
                context.ReportDiagnostic(Diagnostic.Create(
                    NonConstantRequiredValue,
                    nonConstantValue.Location ?? declaration.Location,
                    declaration.Kind == FunctionDeclarationKind.Queue ? "queue" : "topic",
                    nonConstantValue.Name));
            }

            foreach (var missingValue in declaration.GetMissingRequiredValues())
            {
                invalidDeclarations.Add(declaration);
                context.ReportDiagnostic(Diagnostic.Create(
                    MissingRequiredValue,
                    missingValue.Location ?? declaration.Location,
                    declaration.Kind == FunctionDeclarationKind.Queue ? "queue" : "topic",
                    missingValue.Name));
            }
        }

        foreach (var duplicateGroup in functionDeclarations
                     .Where(static declaration => !string.IsNullOrWhiteSpace(declaration.FunctionName))
                     .GroupBy(static declaration => declaration.FunctionName, StringComparer.Ordinal)
                     .Where(static group => group.Skip(1).Any()))
        {
            foreach (var declaration in duplicateGroup)
            {
                invalidDeclarations.Add(declaration);
                context.ReportDiagnostic(Diagnostic.Create(
                    DuplicateFunctionName,
                    declaration.FunctionNameLocation ?? declaration.Location,
                    declaration.FunctionName));
            }
        }

        foreach (var declaration in functionDeclarations.Where(declaration => !invalidDeclarations.Contains(declaration)))
        {
            var generatedSource = GenerateWrapperSource(declaration);
            context.AddSource(GetHintName(declaration), SourceText.From(generatedSource, Encoding.UTF8));
        }
    }

    private static bool IsCandidateAssemblyAttribute(SyntaxNode node)
    {
        if (node is not AttributeSyntax attribute)
        {
            return false;
        }

        return attribute.Parent is AttributeListSyntax attributeList
            && IsAssemblyAttributeList(attributeList);
    }

    private static FunctionDeclaration? CreateDeclaration(
        GeneratorSyntaxContext syntaxContext,
        System.Threading.CancellationToken cancellationToken)
    {
        var attribute = (AttributeSyntax)syntaxContext.Node;
        var kind = GetDeclarationKind(attribute, syntaxContext.SemanticModel, cancellationToken);
        return kind is null
            ? null
            : CreateDeclaration(kind.Value, attribute, syntaxContext.SemanticModel, cancellationToken);
    }

    private static bool IsAssemblyAttributeList(AttributeListSyntax attributeList)
    {
        return attributeList.Target?.Identifier.IsKind(SyntaxKind.AssemblyKeyword) == true;
    }

    private static FunctionDeclarationKind? GetDeclarationKind(
        AttributeSyntax attribute,
        SemanticModel semanticModel,
        System.Threading.CancellationToken cancellationToken)
    {
        var attributeType = GetAttributeType(attribute, semanticModel, cancellationToken);
        return attributeType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) switch
        {
            "global::MiniBus.AzureFunctions.SourceGenerators.Declarations.MiniBusSourceGeneratedServiceBusQueueFunctionAttribute" => FunctionDeclarationKind.Queue,
            "global::MiniBus.AzureFunctions.SourceGenerators.Declarations.MiniBusSourceGeneratedServiceBusTopicFunctionAttribute" => FunctionDeclarationKind.Topic,
            _ => null
        };
    }

    private static INamedTypeSymbol? GetAttributeType(
        AttributeSyntax attribute,
        SemanticModel semanticModel,
        System.Threading.CancellationToken cancellationToken)
    {
        var symbol = semanticModel.GetSymbolInfo(attribute, cancellationToken).Symbol;
        return symbol switch
        {
            IMethodSymbol methodSymbol => methodSymbol.ContainingType,
            INamedTypeSymbol namedTypeSymbol => namedTypeSymbol,
            _ => semanticModel.GetTypeInfo(attribute, cancellationToken).Type as INamedTypeSymbol
        };
    }

    private static FunctionDeclaration CreateDeclaration(
        FunctionDeclarationKind kind,
        AttributeSyntax attribute,
        SemanticModel semanticModel,
        System.Threading.CancellationToken cancellationToken)
    {
        var values = new Dictionary<string, AttributeValue>(StringComparer.OrdinalIgnoreCase);
        var positionalNames = kind == FunctionDeclarationKind.Queue
            ? new[] { "functionName", "queueName", "connection" }
            : new[] { "functionName", "topicName", "subscriptionName", "connection" };
        var positionalIndex = 0;

        foreach (var argument in attribute.ArgumentList?.Arguments ?? default(SeparatedSyntaxList<AttributeArgumentSyntax>))
        {
            var name = argument.NameColon?.Name.Identifier.ValueText
                ?? argument.NameEquals?.Name.Identifier.ValueText;

            if (string.IsNullOrEmpty(name))
            {
                if (positionalIndex >= positionalNames.Length)
                {
                    continue;
                }

                name = positionalNames[positionalIndex];
                positionalIndex++;
            }

            values[name!] = CreateAttributeValue(semanticModel, argument, cancellationToken);
        }

        values.TryGetValue("functionName", out var functionName);
        values.TryGetValue("connection", out var connection);

        if (kind == FunctionDeclarationKind.Queue)
        {
            values.TryGetValue("queueName", out var queueName);
            return FunctionDeclaration.Queue(
                functionName.Value,
                functionName.Location,
                functionName.IsNonConstant,
                queueName.Value,
                queueName.Location,
                queueName.IsNonConstant,
                connection.Value,
                connection.Location,
                connection.IsNonConstant,
                attribute.GetLocation());
        }

        values.TryGetValue("topicName", out var topicName);
        values.TryGetValue("subscriptionName", out var subscriptionName);

        return FunctionDeclaration.Topic(
            functionName.Value,
            functionName.Location,
            functionName.IsNonConstant,
            topicName.Value,
            topicName.Location,
            topicName.IsNonConstant,
            subscriptionName.Value,
            subscriptionName.Location,
            subscriptionName.IsNonConstant,
            connection.Value,
            connection.Location,
            connection.IsNonConstant,
            attribute.GetLocation());
    }

    private static AttributeValue CreateAttributeValue(
        SemanticModel semanticModel,
        AttributeArgumentSyntax argument,
        System.Threading.CancellationToken cancellationToken)
    {
        var constantValue = semanticModel.GetConstantValue(argument.Expression, cancellationToken);
        if (!constantValue.HasValue)
        {
            return new AttributeValue(value: null, argument.Expression.GetLocation(), isNonConstant: true);
        }

        if (constantValue.Value is string value)
        {
            return new AttributeValue(value, argument.Expression.GetLocation(), isNonConstant: false);
        }

        return constantValue.Value is null
            ? new AttributeValue(value: null, argument.Expression.GetLocation(), isNonConstant: false)
            : new AttributeValue(value: null, argument.Expression.GetLocation(), isNonConstant: true);
    }

    private static string GenerateWrapperSource(FunctionDeclaration declaration)
    {
        var className = GetClassName(declaration.FunctionName);
        var functionName = SymbolDisplay.FormatLiteral(declaration.FunctionName, quote: true);
        var connection = SymbolDisplay.FormatLiteral(declaration.Connection, quote: true);
        var trigger = declaration.Kind == FunctionDeclarationKind.Queue
            ? $"{SymbolDisplay.FormatLiteral(declaration.QueueName, quote: true)}, Connection = {connection}"
            : $"{SymbolDisplay.FormatLiteral(declaration.TopicName, quote: true)}, {SymbolDisplay.FormatLiteral(declaration.SubscriptionName, quote: true)}, Connection = {connection}";

        return $$"""
// <auto-generated/>
#nullable enable

namespace MiniBus.AzureFunctions.__Generated
{
    public sealed class {{className}}
    {
        private readonly global::MiniBus.AzureFunctions.Processing.MiniBusProcessor _processor;

        public {{className}}(global::MiniBus.AzureFunctions.Processing.MiniBusProcessor processor)
        {
            _processor = processor;
        }

        [global::Microsoft.Azure.Functions.Worker.Function({{functionName}})]
        public global::System.Threading.Tasks.Task RunAsync(
            [global::Microsoft.Azure.Functions.Worker.ServiceBusTrigger({{trigger}})] global::Azure.Messaging.ServiceBus.ServiceBusReceivedMessage message,
            global::Microsoft.Azure.Functions.Worker.ServiceBusMessageActions actions,
            global::System.Threading.CancellationToken cancellationToken)
        {
            return _processor.ProcessAsync(message, actions, cancellationToken);
        }
    }
}
""";
    }

    private static string GetHintName(FunctionDeclaration declaration)
    {
        return $"{GetClassName(declaration.FunctionName)}.g.cs";
    }

    private static string GetClassName(string functionName)
    {
        return $"MiniBusGenerated{SanitizeIdentifier(functionName)}_{ComputeStableHash(functionName)}Function";
    }

    private static string SanitizeIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (builder.Length == 0 || !IsIdentifierStartCharacter(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    private static bool IsIdentifierStartCharacter(char character)
    {
        return char.IsLetter(character) || character == '_';
    }

    private static string ComputeStableHash(string value)
    {
        unchecked
        {
            var hash = 2166136261u;
            foreach (var character in value)
            {
                hash ^= character;
                hash *= 16777619u;
            }

            return hash.ToString("X8");
        }
    }

    private readonly struct AttributeValue
    {
        public AttributeValue(string? value, Location? location, bool isNonConstant)
        {
            Value = value;
            Location = location;
            IsNonConstant = isNonConstant;
        }

        public string? Value { get; }

        public Location? Location { get; }

        public bool IsNonConstant { get; }
    }

    private enum FunctionDeclarationKind
    {
        Queue,
        Topic
    }

    private sealed class FunctionDeclaration
    {
        private FunctionDeclaration(
            FunctionDeclarationKind kind,
            string? functionName,
            Location? functionNameLocation,
            bool functionNameIsNonConstant,
            string? queueName,
            Location? queueNameLocation,
            bool queueNameIsNonConstant,
            string? topicName,
            Location? topicNameLocation,
            bool topicNameIsNonConstant,
            string? subscriptionName,
            Location? subscriptionNameLocation,
            bool subscriptionNameIsNonConstant,
            string? connection,
            Location? connectionLocation,
            bool connectionIsNonConstant,
            Location location)
        {
            Kind = kind;
            FunctionName = functionName ?? string.Empty;
            FunctionNameLocation = functionNameLocation;
            FunctionNameIsNonConstant = functionNameIsNonConstant;
            QueueName = queueName ?? string.Empty;
            QueueNameLocation = queueNameLocation;
            QueueNameIsNonConstant = queueNameIsNonConstant;
            TopicName = topicName ?? string.Empty;
            TopicNameLocation = topicNameLocation;
            TopicNameIsNonConstant = topicNameIsNonConstant;
            SubscriptionName = subscriptionName ?? string.Empty;
            SubscriptionNameLocation = subscriptionNameLocation;
            SubscriptionNameIsNonConstant = subscriptionNameIsNonConstant;
            Connection = connection ?? string.Empty;
            ConnectionLocation = connectionLocation;
            ConnectionIsNonConstant = connectionIsNonConstant;
            Location = location;
        }

        public FunctionDeclarationKind Kind { get; }

        public string FunctionName { get; }

        public Location? FunctionNameLocation { get; }

        public bool FunctionNameIsNonConstant { get; }

        public string QueueName { get; }

        public Location? QueueNameLocation { get; }

        public bool QueueNameIsNonConstant { get; }

        public string TopicName { get; }

        public Location? TopicNameLocation { get; }

        public bool TopicNameIsNonConstant { get; }

        public string SubscriptionName { get; }

        public Location? SubscriptionNameLocation { get; }

        public bool SubscriptionNameIsNonConstant { get; }

        public string Connection { get; }

        public Location? ConnectionLocation { get; }

        public bool ConnectionIsNonConstant { get; }

        public Location Location { get; }

        public static FunctionDeclaration Queue(
            string? functionName,
            Location? functionNameLocation,
            bool functionNameIsNonConstant,
            string? queueName,
            Location? queueNameLocation,
            bool queueNameIsNonConstant,
            string? connection,
            Location? connectionLocation,
            bool connectionIsNonConstant,
            Location location)
        {
            return new FunctionDeclaration(
                FunctionDeclarationKind.Queue,
                functionName,
                functionNameLocation,
                functionNameIsNonConstant,
                queueName,
                queueNameLocation,
                queueNameIsNonConstant,
                topicName: null,
                topicNameLocation: null,
                topicNameIsNonConstant: false,
                subscriptionName: null,
                subscriptionNameLocation: null,
                subscriptionNameIsNonConstant: false,
                connection,
                connectionLocation,
                connectionIsNonConstant,
                location);
        }

        public static FunctionDeclaration Topic(
            string? functionName,
            Location? functionNameLocation,
            bool functionNameIsNonConstant,
            string? topicName,
            Location? topicNameLocation,
            bool topicNameIsNonConstant,
            string? subscriptionName,
            Location? subscriptionNameLocation,
            bool subscriptionNameIsNonConstant,
            string? connection,
            Location? connectionLocation,
            bool connectionIsNonConstant,
            Location location)
        {
            return new FunctionDeclaration(
                FunctionDeclarationKind.Topic,
                functionName,
                functionNameLocation,
                functionNameIsNonConstant,
                queueName: null,
                queueNameLocation: null,
                queueNameIsNonConstant: false,
                topicName,
                topicNameLocation,
                topicNameIsNonConstant,
                subscriptionName,
                subscriptionNameLocation,
                subscriptionNameIsNonConstant,
                connection,
                connectionLocation,
                connectionIsNonConstant,
                location);
        }

        public IEnumerable<(string Name, Location? Location)> GetNonConstantRequiredValues()
        {
            if (FunctionNameIsNonConstant)
            {
                yield return ("functionName", FunctionNameLocation);
            }

            if (ConnectionIsNonConstant)
            {
                yield return ("connection", ConnectionLocation);
            }

            if (Kind == FunctionDeclarationKind.Queue)
            {
                if (QueueNameIsNonConstant)
                {
                    yield return ("queueName", QueueNameLocation);
                }

                yield break;
            }

            if (TopicNameIsNonConstant)
            {
                yield return ("topicName", TopicNameLocation);
            }

            if (SubscriptionNameIsNonConstant)
            {
                yield return ("subscriptionName", SubscriptionNameLocation);
            }
        }

        public IEnumerable<(string Name, Location? Location)> GetMissingRequiredValues()
        {
            if (!FunctionNameIsNonConstant && string.IsNullOrWhiteSpace(FunctionName))
            {
                yield return ("functionName", FunctionNameLocation);
            }

            if (!ConnectionIsNonConstant && string.IsNullOrWhiteSpace(Connection))
            {
                yield return ("connection", ConnectionLocation);
            }

            if (Kind == FunctionDeclarationKind.Queue)
            {
                if (!QueueNameIsNonConstant && string.IsNullOrWhiteSpace(QueueName))
                {
                    yield return ("queueName", QueueNameLocation);
                }

                yield break;
            }

            if (!TopicNameIsNonConstant && string.IsNullOrWhiteSpace(TopicName))
            {
                yield return ("topicName", TopicNameLocation);
            }

            if (!SubscriptionNameIsNonConstant && string.IsNullOrWhiteSpace(SubscriptionName))
            {
                yield return ("subscriptionName", SubscriptionNameLocation);
            }
        }
    }
}
